### ISSUE TITLE
Warning: Failed prop type: Invalid prop `routes` of type `function` supplied to `Sitemap`, expected `object`.     in Sitemap (at Sitemap.js:22)

### ISSUE THREAD

**Issue by jmyager** [kapilpau/react-dynamic-sitemap#6]
Thanks for the great plugin! I'm having a little bit of trouble setting it up. I am attempting to provide my Routes component as the routes proptype, but receiving this error:

Warning: Failed prop type: Invalid prop `routes` of type `function` supplied to `Sitemap`, expected `object`.
    in Sitemap (at Sitemap.js:22)
    
  It seems an object is expected instead? I'm not clear on what the syntax of this object should look like.

Thanks!
![screenshot](https://user-images.githubusercontent.com/27778084/108547369-6345cd80-72b8-11eb-9c84-ad11c49efd28.png)

**Comment by kapilpau** [comment]
Hi @jmyager 

Please remove the render() from the routes component, so just 

```js
class Routes extends React.Component {
return (
<Switch>
...
</Switch>
)
}
```

**Comment by jmyager** [comment]
Thanks for the quick response!

Unfortunately, removing the render creates an invalid class component. I can easily change to a functional component, but the error persists when doing so.

![screenshot](https://user-images.githubusercontent.com/27778084/108548365-bbc99a80-72b9-11eb-973c-9634dbe7e8c4.png)

**Comment by kapilpau** [comment]
@jmyager sorry, yeah was thinking about functional components. I don't know why you're getting an error with the second image. Could you send the error output?

**Comment by jmyager** [comment]
No problemo. And sure thing, the error I'm seeing is below

![image](https://user-images.githubusercontent.com/27778084/108558099-71e7b100-72c7-11eb-9b0e-e98b17c21db6.png)

I was able to silence it by removing the required propType line for routes

![image](https://user-images.githubusercontent.com/27778084/108558178-8af06200-72c7-11eb-886c-732150ceb07c.png)

However, even after getting rid of that error, I still can't seem to get my sitemap to render correctly. 

![image](https://user-images.githubusercontent.com/27778084/108558235-a0658c00-72c7-11eb-9b7e-c4bdc656b5c0.png)


Thanks again for your help!

**Comment by kapilpau** [comment]
Hi, sorry for the delay in replying, Did you manager to resolve this?

**Comment by jmyager** [comment]
No problem. I have not yet resolved it.

**Comment by kapilpau** [comment]
Apologies for the delay in responding. So the second issue (where the sitemap isn't populated) is because you're missing params from your routes, these are documented at the bottom of the [readme](https://github.com/kapilpau/react-dynamic-sitemap), and they will not get populated without setting `sitemapIndex` to `true`, at the very least.

Regarding your first error, I will update the code to fix the proptype

**Comment by kapilpau** [comment]
I have pushed the update, please let me know if this fixes it

**Comment by kapilpau** [comment]
@jmyager this ticket has gone quiet so will close in 2 weeks unless I hear otherwise, hopefully it was fixed for you

**Comment by kapilpau** [comment]
@jmyager assuming this has been resolved so I am closing this issue. If you are still experiencing this issue, feel free to reopen it
