### ISSUE TITLE
No sitemap.xml file ?

### ISSUE THREAD

**Issue by OooCleMooO** [kapilpau/react-dynamic-sitemap#7]
Hi,

Thanks for this sitemap library ! But seems to not create an sitemap.xml file, and SEO engine need this file to check website sitemap. Have I missed something with library use ?

**Comment by kapilpau** [comment]
Hi @OooCleMooO, this package is a dynamic sitemap generator, therefore it doesn't create a file, rather it generates it at call time, so you need to add a route for it, where it will serve it. You can then save that file and server it yourself if you wish. The [readme](https://github.com/kapilpau/react-dynamic-sitemap#usage) has the full usage documentation

**Comment by OooCleMooO** [comment]
@kapilpau I understood ! Thanks a lot for your explanations :)

**Comment by kapilpau** [comment]
Great, thanks, are you happy for me to close this issue then?
