### ISSUE TITLE
Empty Page

### ISSUE THREAD

**Issue by MahdiKarimipour** [kapilpau/react-dynamic-sitemap#8]

**Comment by kapilpau** [comment]
Hi @MahdiKarimipour,

Thanks for using react-dynamic sitemap. I see you deleted the contents of this issue so I am assuming you fixed the issue yourself. If that's the case, could you please re-add all of the details of the ticket, and add a comment about how you fixed it, in case someone else has the same issue later on, they can use your ticket to fix their issue.

Thanks
